//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a Chumpinate.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:Chumpinate.chug Chumpinate-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:Chumpinate.chug Chumpinate-test.ck -v3`
//--------------------------------------------------------------------

// instantiate a Chumpinate
// Package.help();
// Package pkg("test-pkg");

// "nick" => pkg.authors;

// ["nick", "ge"] => pkg.authors;

// "www.www.com" => pkg.homepage;
// "www.www.com" => pkg.repository;

// "mit" => pkg.license;
// "a description" => pkg.description;

// ["wow", "much", "keyword"] => pkg.keywords;

// "./" => pkg.generatePackageDefinition;


PackageVersion.help();
PackageVersion ver("1.0.0");
// PackageVersion ver;

"10.2" => ver.apiVersion;
<<< ver.apiVersion() >>>;

"1.5.4.2" => ver.languageVersionMin;
<<< ver.languageVersionMin() >>>;

"1.5.4.3" => ver.languageVersionMax;
<<< ver.languageVersionMax() >>>;

"linux" => ver.os;
<<< ver.os() >>>;


// Add itself
ver.addFile("./test.txt");
ver.addDataFile("./test.txt");
ver.addExampleFile("./test.txt", "test");
ver.addDocsFile("./test.txt");
ver.addDepsFile("./test.txt");

ver.generateVersion("./", "poop", "www.");

